language: c

compiler:
    - clang
    - gcc

before_install:
    - sudo apt-get install libpcap0.8 libpcap0.8-dev valgrind

script:
    - make && make check

notifications:
    email:
      - hyzwowtools@gmail.com
